#!/bin/bash

# Start a new screen session named "my_session_name"
screen -dmS testbro

# Send a command to the screen session
screen -S testbro -X stuff "ffmpeg -i udp://227.1.1.111:5030 -c:v libx264 -c:a aac -strict experimental Brazil-vs-spanyol_7.mp4$(printf \\r)"

# Sleep for a few seconds to allow the command to run
sleep 300

# Cancel the command by sending an interrupt signal
screen -S testbro -X stuff $'\003'  # Send Ctrl+C

# Sleep again to allow the command to respond to Ctrl+C
sleep 300

# Terminate the screen session
screen -S testbro -X quit

